
'use server';

import { createClient } from '@supabase/supabase-js';

/**
 * Server Action to generate a secure signed URL using the Supabase Service Role Key.
 * This bypasses RLS policies and allows Firebase-authenticated users to access private files.
 * 
 * @param filePath - The path to the file in the bucket (e.g., 'uid/timestamp-file.pdf')
 * @returns The signed URL or an error.
 */
export async function getSignedUrlAction(filePath: string) {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceRoleKey) {
    console.error('[Server Action] Configuration Missing: NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
    throw new Error('Storage service configuration error.');
  }

  // Initialize a server-side client with the Service Role Key
  const supabaseAdmin = createClient(supabaseUrl, serviceRoleKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false
    }
  });

  // Clean the path: remove bucket name if it was accidentally prepended
  let cleanPath = filePath;
  if (cleanPath.startsWith('documents/')) {
    cleanPath = cleanPath.replace('documents/', '');
  }

  console.log('[Server Action] Generating Signed URL for:', cleanPath);

  const { data, error } = await supabaseAdmin.storage
    .from('documents')
    .createSignedUrl(cleanPath, 3600); // 1 hour expiry

  if (error) {
    console.error('[Server Action] Supabase Error:', error.message);
    throw new Error(`Failed to generate access link: ${error.message}`);
  }

  if (!data?.signedUrl) {
    throw new Error('No URL generated by storage server.');
  }

  return { signedUrl: data.signedUrl };
}
